import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import WorkTile from "../components/WorkTile";

export default function Home() {
  return (
    <div id="wrapper">
      <Head>
        <title>Soren SZABO - Gameplay Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      {/* <!-- Main --> */}
      <div id="main">
        <div className="inner">
          <header>
            <h1>Welcome.</h1>
            <p>
              I&#39;m a gameplay programmer based in Paris, France.
              <br />
              Using my experience to build exciting new ways to game on every
              platform. Here is some of my work
            </p>
          </header>
          <section className="tiles">
            <WorkTile
              data={{
                classStyle: "style1",
                href: "/work/celestrail",
                backgroundImage: "ICON_CELESTRAIL.jpg",
                title: "Celestrail",
                heading:
                  "VR graduation group project using Unity. Made for Oculus/Meta Quest",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style2",
                href: "/work/the-workplace",
                backgroundImage: "ICON_THEWORKPLACE.jpg",
                title: "The Workplace",
                heading:
                  "Programmer only group project. Made in Unreal Engine 4 for PC",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style3",
                href: "/work/umbra",
                backgroundImage: "ICON_UMBRA.jpg",
                title: "Umbra",
                heading:
                  "Game Design on a 2D Metroidvania game, made for PC using Unity",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style4",
                href: "/work/ddd",
                backgroundImage: "ICON_DDD.jpg",
                title: "DashDashDASH!",
                heading: "Game jam project, 2D hyper casual game using Unity",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style5",
                href: "/work/dmd",
                backgroundImage: "ICON_DMD.jpg",
                title: "Dwarves Must Die",
                heading:
                  "Game jam project, hack'n'slash with RPG mechanics, made using Unity",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style6",
                href: "/work/rushed",
                backgroundImage: "ICON_RUSHED.jpg",
                title: "Rushed",
                heading: "Solo project, 3D puzzle game using Unity",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style2",
                href: "/work/sc3095",
                backgroundImage: "ICON_SC3095.jpg",
                title: "Star Crusader 3095",
                heading:
                  "2D Run'n 'gun with online save capability. Made using Haxe and mongoDB",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style3",
                href: "/work/ss",
                backgroundImage: "ICON_SS.jpg",
                title: "Shogun Showdown",
                heading:
                  "Online card fighting game with asynchronous server. Built using JavaScript and nodeJS",
              }}
            ></WorkTile>
            <WorkTile
              data={{
                classStyle: "style1",
                href: "/work/athyo",
                backgroundImage: "ICON_ATHYO.png",
                title: "Athyo",
                heading:
                  "Solo mini game project, shoot&apos;em up made with ActionScript 3 and Adobe Animate CC",
              }}
            ></WorkTile>
          </section>
        </div>
      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      <Footer></Footer>
    </div>
  );
}
